### ISSUE TITLE
Problem with add_inter_chrom_beads.sh

### ISSUE THREAD

**Issue by bioyuyang** [Chrom3D/Chrom3D#7]
Hi,
Thanks for the nice tools.
I followed your nature protocol got a problem when I combine inter and intra gtrack with **_add_inter_chrom_beads.sh_**.

My command is:  **bash add_inter_chrom_beads.sh  ES_intra_chromosome_w_LADs.gtrack   ../ES.domain.chr.inter.txt.sig  ES_intra_inter_chromosome_w_LADs.gtrack**

head  ES_intra_chromosome_w_LADs.gtrack                                                                                     
##gtrack version: 1.0
##track type: linked segments
###seqid	start	end	id	radius	periphery	edges
chr1	0	3500000	chr1:0-3500000	1	0	.
chr1	3000000	3500000	chr1:3000000-3500000	1	0	chr1:90000000-90500000
chr1	3500000	4000000	chr1:3500000-4000000	1	0	chr1:90000000-90500000
chr1	4000000	4500000	chr1:4000000-4500000	1	0	chr1:90000000-90500000
chr1	4500000	5000000	chr1:4500000-5000000	1	0	chr1:90000000-90500000
chr1	5000000	5500000	chr1:5000000-5500000	1	1	.
chr1	5500000	6000000	chr1:5500000-6000000	1	1	.

head  ../ES.domain.chr.inter.txt.sig
chr1	17000000	17500000	chr10	67500000	68000000	0.000152649039785
chr1	17500000	18000000	chr10	67500000	68000000	0.0
chr1	18000000	18500000	chr10	67500000	68000000	2.93012068598e-06
chr1	22000000	22500000	chr10	92500000	93000000	0.00145193466443
chr1	110000000	110500000	chr10	105500000	106000000	6.30588081218e-06
chr1	196500000	197000000	chr10	129500000	129993255	0.00327782353218
chr1	197000000	197195432	chr10	129500000	129993255	0.0
chr1	150000000	150500000	chr11	93500000	94000000	0.00106887476924
chr1	197000000	197195432	chr11	121500000	121843856	0.0
chr1	9000000	9500000	chr12	22000000	22500000	1.09189785969e-06

**The error report look like this:**
Traceback (most recent call last):
  File "inter_chrom_beads.py", line 64, in <module>
    right = str(end2_with_bead[i]).split()[7]
  File "/usr/local/anaconda/lib/python2.7/site-packages/pybedtools-0.7.7-py2.7-linux-x86_64.egg/pybedtools/bedtool.py", line 1097, in __getitem__
    return list(islice(self, key, key + 1))[0]
IndexError: list index out of range

**Comment by tharvesh** [comment]
Hi bioyuyang,

Could you please make sure that `../ES.domain.chr.inter.txt.sig` is a tab-separated file?

Thanks

**Comment by bioyuyang** [comment]
Thanks for the reply.
I checked format. It's tab-separated file.
I got it from:
```
NCHG -i -p ES.domain.chr.inter.txt > ES.domain.chr.inter.txt.out
python  NCHG_fdr_oddratio_calc.py  ES.domain.chr.inter.txt.out   fdr_bh 2 0.01 > ES.domain.chr.inter.txt.sig 
```

**Comment by tharvesh** [comment]
Hi bioyuyang,

Could you please check the version of the bedtools?

Thanks

**Comment by sespesogil** [comment]
I am also having problems here. Not sure if it is the bedtools version (bedtools/2.25.0) . The error message says : 

BEDTools Error: The requested bed file (/tmp/pybedtools.0wZ2rZ.tmp) could not be opened. Exiting!
Traceback (most recent call last):
  File "inter_chrom_beads.py", line 63, in <module>
  File "/*/packages/*/py_packages/2.7/lib/python2.7/site-packages/pybedtools/bedtool.py", line 990, in __getitem__
  File "cbedtools.pyx", line 671, in pybedtools.cbedtools.IntervalFile.__next__ (pybedtools/cbedtools.cpp:9269)
pybedtools.cbedtools.BedToolsFileError: Error opening file


Any guess? Thanks a lot!

**Comment by tharvesh** [comment]
Hi pl4ygroundl0ve

Could you please check if you have enough space in your /tmp folder and rw permission, and also try updating bedtools and pybedtools package.

Thanks

**Comment by sespesogil** [comment]
Yup, it was in fact a problem of permissions. I have solved it installing my own pybedtools and changing inter_chrom_beads.py to proper link the package. Now working totally fine. Thanks!!!
